theme: doks
baseurl: https://doks.netlify.app/
canonifyURLs: no
disableAliases: yes
disableHugoGeneratorInject: yes
enableEmoji: yes
enableGitInfo: no
enableRobotsTXT: yes
paginate: 7
rssLimit: 10
defaultContentLanguage: en
disableLanguages:
  - de
  - nl
outputs:
  home:
    - HTML
    - RSS
    - REDIRECTS
    - HEADERS
  section:
    - HTML
    - RSS
    - SITEMAP
mediaTypes:
  text/netlify:
    delimiter: ''
    suffixes: ''
outputFormats:
  HEADERS:
    baseName: _headers
    isPlainText: yes
    mediaType: text/netlify
    notAlternative: yes
  REDIRECTS:
    baseName: _redirects
    isPlainText: yes
    mediaType: text/netlify
    notAlternative: yes
  SITEMAP:
    baseName: sitemap
    isHTML: no
    isPlainText: yes
    mediaType: application/xml
    noUgly: yes
    rel: sitemap
caches:
  getjson:
    dir: :cacheDir/:project
    maxAge: 10s
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
taxonomies:
  category: categories
  contributor: contributors
  tag: tags
permalinks:
  blog: /blog/:title/
minify:
  tdewolff:
    html:
      keepWhitespace: no
related:
  includeNewer: yes
  indices:
    - name: categories
      weight: 100
    - name: tags
      weight: 80
    - name: date
      weight: 10
  threshold: 80
  toLower: no
module:
  hugoVersion:
    extended: yes
    max: ''
    min: 0.80.0
  mounts:
    - source: assets
      target: assets
    - source: static
      target: static
    - source: layouts
      target: layouts
    - source: node_modules/flexsearch
      target: assets/js/vendor/flexsearch
    - source: node_modules/katex
      target: assets/js/vendor/katex
    - source: node_modules/mermaid
      target: assets/js/vendor/mermaid
    - source: node_modules/@hyas/images/layouts
      target: layouts
