title: "MCnebula2 workflow for LC-MS/MS dataset analysis"
bibliography: '`r system.file("extdata", "library.bib", package = "MCnebula2")`'
csl: '`r system.file("extdata", "vancouver.csl", package = "MCnebula2")`'
output:
  bookdown::pdf_document2:
    keep_tex: false
    toc: true
    toc_depth: 3
    latex_engine: xelatex
    df_print: kable
